[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
ic42n = "9d91Y1xkD67Uss7Uh9aVKFj9jZZbBVCnS9NdfARLh1Te"

[programs.devnet]
ic42n = "9d91Y1xkD67Uss7Uh9aVKFj9jZZbBVCnS9NdfARLh1Te"

[programs.mainnet]
ic42n = "ic429goRDdS7BXEDYr2nZeAYMxtT6FL3AsB3sneaSu7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "https://api.mainnet-beta.solana.com"
wallet = "~/.config/solana/id.json"

[scripts]
